import os
import re
import tempfile
from datetime import datetime

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)
from reportlab.lib.styles import getSampleStyleSheet


# ── Helpers ──────────────────────────────────────────────────────────────────

def sanitize_filename(name):
    """
    Removes characters that are unsafe in filenames.
    'Tata Motors & Sons' → 'Tata_Motors__Sons'
    Prevents file system errors on all platforms including Streamlit Cloud.
    """
    name = re.sub(r'[^\w\s-]', '', name)
    name = name.strip().replace(' ', '_')
    return name


def clean_text_for_pdf(text):
    """
    Replaces characters ReportLab's default font cannot render.
    Fixes the ■ symbol that appears instead of ₹ in the current PDF.
    """
    text = text.replace("₹", "Rs.")
    text = text.replace("\u20b9", "Rs.")  # Unicode rupee sign
    text = text.replace("■", "Rs.")       # Broken rendering fallback
    text = text.replace("\u2019", "'")    # Right single quotation mark
    text = text.replace("\u2018", "'")    # Left single quotation mark
    text = text.replace("\u201c", '"')    # Left double quotation mark
    text = text.replace("\u201d", '"')    # Right double quotation mark
    text = text.replace("\u2013", "-")    # En dash
    text = text.replace("\u2014", "--")   # Em dash
    return text


def extract_source_urls(research_data):
    """
    Pulls all scraped URLs out of the research_data dict.
    Returns a deduplicated list for the sources page.
    """
    urls = []
    seen = set()
    for documents in research_data.values():
        for doc in documents:
            url = doc.get("url", "")
            if url and url not in seen:
                urls.append(url)
                seen.add(url)
    return urls


# ── Main Builder ─────────────────────────────────────────────────────────────

def create_company_report(company_name, report_text, research_data=None):
    """
    Builds a PDF intelligence report and saves it to the system temp directory.
    Using tempfile ensures compatibility with Streamlit Cloud's read-only filesystem.

    Parameters
    ----------
    company_name  : str  — Used for filename and cover page title
    report_text   : str  — Markdown-style report from synthesizer
    research_data : dict — Original research dict used to extract source URLs

    Returns
    -------
    str — Absolute path to the saved PDF file
    """

    # ── Filename ─────────────────────────────────────────────────────────────
    # Save to temp dir — works on local machine and Streamlit Cloud equally
    safe_name = sanitize_filename(company_name)
    tmp_dir   = tempfile.gettempdir()
    filename  = os.path.join(tmp_dir, f"{safe_name}_Intelligence_Report.pdf")

    pdf    = SimpleDocTemplate(filename)
    styles = getSampleStyleSheet()
    story  = []

    # ── Cover Page ────────────────────────────────────────────────────────────
    story.append(Spacer(1, 60))

    story.append(
        Paragraph(
            f"{company_name} Intelligence Report",
            styles["Title"]
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "Generated by ResearchMind",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 10))

    # Date added to cover page
    story.append(
        Paragraph(
            f"Report Date: {datetime.now().strftime('%B %d, %Y')}",
            styles["Normal"]
        )
    )

    story.append(PageBreak())

    # ── Report Sections ───────────────────────────────────────────────────────
    # Clean text before parsing to fix symbol rendering issues
    report_text = clean_text_for_pdf(report_text)
    sections    = report_text.split("##")

    for section in sections:

        section = section.strip()

        if not section:
            continue

        lines   = section.split("\n")
        heading = lines[0].strip()
        body    = "\n".join(lines[1:]).strip()

        if not heading:
            continue

        story.append(
            Paragraph(heading, styles["Heading1"])
        )

        story.append(Spacer(1, 10))

        if body:
            story.append(
                Paragraph(body, styles["BodyText"])
            )

        story.append(Spacer(1, 20))

    # ── Sources Page ──────────────────────────────────────────────────────────
    # Only added if research_data was passed in and contains URLs
    if research_data:
        source_urls = extract_source_urls(research_data)

        if source_urls:
            story.append(PageBreak())

            story.append(
                Paragraph("Sources & References", styles["Heading1"])
            )

            story.append(Spacer(1, 10))

            for i, url in enumerate(source_urls, 1):
                url_clean = clean_text_for_pdf(url)
                story.append(
                    Paragraph(
                        f"{i}. {url_clean}",
                        styles["Normal"]
                    )
                )
                story.append(Spacer(1, 4))

    # ── Build ─────────────────────────────────────────────────────────────────
    pdf.build(story)

    return filename