import os
import re
import tempfile
from datetime import datetime

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak,
    HRFlowable,
    Table,
    TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch


# ── Helpers ───────────────────────────────────────────────────────────────────

def sanitize_filename(name):
    name = re.sub(r'[^\w\s-]', '', name)
    name = name.strip().replace(' ', '_')
    return name


def clean_text_for_pdf(text):
    text = text.replace("₹", "Rs.")
    text = text.replace("\u20b9", "Rs.")
    text = text.replace("■", "Rs.")
    text = text.replace("\u2019", "'")
    text = text.replace("\u2018", "'")
    text = text.replace("\u201c", '"')
    text = text.replace("\u201d", '"')
    text = text.replace("\u2013", "-")
    text = text.replace("\u2014", "--")
    return text


def extract_source_urls(research_data):
    urls = []
    seen = set()
    for documents in research_data.values():
        for doc in documents:
            url = doc.get("url", "")
            if url and url not in seen:
                urls.append(url)
                seen.add(url)
    return urls


def build_rating_badge(body_text, styles):

    RATING_COLORS = {
        "STRONG":   colors.HexColor("#1E7A3B"),
        "MODERATE": colors.HexColor("#B85C00"),
        "WATCH":    colors.HexColor("#B00020"),
    }

    detected_rating = None
    cleaned_lines   = []

    for line in body_text.split("\n"):
        if "Overall Rating:" in line:
            for keyword in RATING_COLORS:
                if keyword in line.upper():
                    detected_rating = keyword
                    break
        else:
            cleaned_lines.append(line)

    if not detected_rating:
        return None, body_text

    badge_text = f"  Overall Rating: {detected_rating}  "

    badge_style = ParagraphStyle(
        "BadgeText",
        parent=styles["Normal"],
        textColor=colors.white,
        fontName="Helvetica-Bold",
        fontSize=11,
    )

    badge_table = Table(
        [[Paragraph(badge_text, badge_style)]],
        colWidths=[2.5 * inch]
    )

    badge_table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), RATING_COLORS[detected_rating]),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING",   (0, 0), (-1, -1), 12),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 12),
    ]))

    remaining_body = "\n".join(cleaned_lines).strip()

    return badge_table, remaining_body


# ── V1.3: Professional Cover Page ─────────────────────────────────────────────
# Replaces the plain text cover with a structured layout:
#   - Full-width navy header bar with company name in white
#   - "Intelligence Report" subtitle below the bar
#   - Thin accent line
#   - Metadata block: Generated by, Report Date, Confidentiality note
# Uses only Table + TableStyle — no new imports needed.
# Transforms first impression from student project to analyst report.

def build_cover_page(company_name, styles, story):

    NAVY = colors.HexColor("#1B2A4A")
    GOLD = colors.HexColor("#C9A84C")

    # ── Top spacer ────────────────────────────────────────────────────────────
    story.append(Spacer(1, 80))

    # ── Navy header bar with company name ─────────────────────────────────────
    company_style = ParagraphStyle(
        "CoverCompany",
        parent=styles["Normal"],
        textColor=colors.white,
        fontName="Helvetica-Bold",
        fontSize=26,
        leading=32,
    )

    header_table = Table(
        [[Paragraph(company_name.upper(), company_style)]],
        colWidths=[6.5 * inch]
    )

    header_table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), NAVY),
        ("TOPPADDING",    (0, 0), (-1, -1), 28),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 28),
        ("LEFTPADDING",   (0, 0), (-1, -1), 24),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 24),
    ]))

    story.append(header_table)

    # ── Gold accent line ──────────────────────────────────────────────────────
    story.append(
        HRFlowable(
            width="100%",
            thickness=3,
            color=GOLD,
            spaceAfter=0,
            spaceBefore=0
        )
    )

    story.append(Spacer(1, 20))

    # ── Subtitle ──────────────────────────────────────────────────────────────
    subtitle_style = ParagraphStyle(
        "CoverSubtitle",
        parent=styles["Normal"],
        textColor=NAVY,
        fontName="Helvetica",
        fontSize=15,
        leading=20,
    )

    story.append(
        Paragraph("Company Intelligence Report", subtitle_style)
    )

    story.append(Spacer(1, 6))

    story.append(
        HRFlowable(
            width="100%",
            thickness=0.5,
            color=colors.HexColor("#CCCCCC"),
            spaceAfter=0
        )
    )

    story.append(Spacer(1, 40))

    # ── Metadata block ────────────────────────────────────────────────────────
    meta_style = ParagraphStyle(
        "CoverMeta",
        parent=styles["Normal"],
        textColor=colors.HexColor("#444444"),
        fontName="Helvetica",
        fontSize=10,
        leading=18,
    )

    story.append(
        Paragraph(
            f"<b>Generated by:</b> ResearchMind AI",
            meta_style
        )
    )

    story.append(
        Paragraph(
            f"<b>Report Date:</b> {datetime.now().strftime('%B %d, %Y')}",
            meta_style
        )
    )

    story.append(
        Paragraph(
            "<b>Classification:</b> Confidential — For Internal Use Only",
            meta_style
        )
    )

    story.append(Spacer(1, 50))

    # ── Bottom branding line ──────────────────────────────────────────────────
    story.append(
        HRFlowable(
            width="100%",
            thickness=0.5,
            color=colors.HexColor("#CCCCCC"),
            spaceAfter=10
        )
    )

    brand_style = ParagraphStyle(
        "CoverBrand",
        parent=styles["Normal"],
        textColor=colors.HexColor("#999999"),
        fontName="Helvetica",
        fontSize=8,
    )

    story.append(
        Paragraph(
            "This report was automatically generated using AI-powered research. "
            "Verify all data with primary sources before making business decisions.",
            brand_style
        )
    )

    story.append(PageBreak())


# ── Main Builder ──────────────────────────────────────────────────────────────

def create_company_report(company_name, report_text, research_data=None):

    safe_name = sanitize_filename(company_name)
    tmp_dir   = tempfile.gettempdir()
    filename  = os.path.join(tmp_dir, f"{safe_name}_Intelligence_Report.pdf")

    pdf = SimpleDocTemplate(
        filename,
        leftMargin=0.85 * inch,
        rightMargin=0.85 * inch,
        topMargin=1 * inch,
        bottomMargin=1 * inch
    )
    styles = getSampleStyleSheet()
    story  = []

    # ── V1.3: Professional cover page ─────────────────────────────────────────
    build_cover_page(company_name, styles, story)

    # ── Report Sections ───────────────────────────────────────────────────────
    report_text = clean_text_for_pdf(report_text)
    sections    = report_text.split("##")

    for section in sections:

        section = section.strip()

        if not section:
            continue

        lines   = section.split("\n")
        heading = lines[0].strip()
        body    = "\n".join(lines[1:]).strip()

        if not heading:
            continue

        story.append(
            Paragraph(heading, styles["Heading1"])
        )

        story.append(Spacer(1, 8))

        story.append(
            HRFlowable(
                width="100%",
                thickness=0.5,
                color=colors.HexColor("#CCCCCC"),
                spaceAfter=6
            )
        )

        if body:

            if "Overall Rating:" in body:

                badge, remaining_body = build_rating_badge(body, styles)

                if badge:
                    story.append(badge)
                    story.append(Spacer(1, 10))

                if remaining_body:
                    story.append(
                        Paragraph(remaining_body, styles["BodyText"])
                    )

            else:
                story.append(
                    Paragraph(body, styles["BodyText"])
                )

        story.append(Spacer(1, 20))

    # ── Sources Page ──────────────────────────────────────────────────────────
    if research_data:
        source_urls = extract_source_urls(research_data)

        if source_urls:
            story.append(PageBreak())

            story.append(
                Paragraph("Sources & References", styles["Heading1"])
            )

            story.append(
                HRFlowable(
                    width="100%",
                    thickness=0.5,
                    color=colors.HexColor("#CCCCCC"),
                    spaceAfter=6
                )
            )

            story.append(Spacer(1, 6))

            for i, url in enumerate(source_urls, 1):
                url_clean = clean_text_for_pdf(url)
                story.append(
                    Paragraph(
                        f"{i}. {url_clean}",
                        styles["Normal"]
                    )
                )
                story.append(Spacer(1, 4))

    # ── Build ─────────────────────────────────────────────────────────────────
    pdf.build(story)

    return filename